### ISSUE TITLE
Mocking doesn't seem to work with methods named `toXYZ`

### ISSUE THREAD

**Issue by josephearl** [eratio08/vitest-mock-extended#268]
I have an interface like so:

```
interface Foo {
  toJSON(): object
}
```

When trying to mock this:

```
const mockFoo = mock<Foo>();
mockFoo.toJSON.mockReturnValue({ "key": "value" });
```

I get an error: `TypeError: mockFoo.toJSON.mockReturnValue is not a function`.

However if I change the method name on the interface from `toJSON()` to just `json()` and the mock to `mockFoo.json.mockReturnValue({ "key": "value" })` then it works as expected.

As far as I can see it is purely the function name that causes it.

**Comment by eratio08** [comment]
This might haven been caused by https://github.com/eratio08/vitest-mock-extended/commit/31ea7aaebab51fc2f418ba210db6ca153166a1c3. I guess I will need an option on the mock if toJSON should call the original or not.

**Comment by josephearl** [comment]
Amazing 🤩 thanks, can confirm the new version fixes my issue
